import type { 
  User, Pet, Trainer, Booking, PetStatus, Notification, Task, DailyActivity, 
  MoodEntry, CarePackage, Message, Review, NotificationPreferences 
} from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john@example.com",
    fullName: "John Smith",
    phone: "1234567890",
    role: "owner",
    avatar: "/man-profile.png",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "sarah@example.com",
    fullName: "Sarah Johnson",
    phone: "0987654321",
    role: "trainer",
    avatar: "/woman-trainer-profile.jpg",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    email: "mike@example.com",
    fullName: "Mike Wilson",
    phone: "5555555555",
    role: "trainer",
    avatar: "/man-trainer-profile.jpg",
    createdAt: new Date("2024-02-10"),
  },
]

export const mockPets: Pet[] = [
  {
    id: "1",
    ownerId: "1",
    name: "Max",
    species: "dog",
    breed: "Golden Retriever",
    age: 3,
    medicalNotes: "Allergic to chicken",
    photo: "/golden-retriever.png",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    ownerId: "1",
    name: "Luna",
    species: "cat",
    breed: "Persian",
    age: 2,
    photo: "/fluffy-persian-cat.png",
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "3",
    ownerId: "1",
    name: "Buddy",
    species: "dog",
    breed: "Labrador",
    age: 5,
    medicalNotes: "Takes daily vitamins",
    photo: "/labrador-dog.png",
    createdAt: new Date("2024-02-05"),
  },
]

export const mockTrainers: Trainer[] = [
  {
    id: "1",
    userId: "2",
    bio: "Certified dog trainer with 10+ years of experience. Specializing in behavioral training and puppy development.",
    experience: 10,
    certifications: ["CPDT-KA", "AKC CGC Evaluator"],
    services: ["Basic Training", "Behavioral Modification", "Puppy Training"],
    pricing: 75,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    rating: 4.9,
  },
  {
    id: "2",
    userId: "3",
    bio: "Animal behavior specialist focusing on both dogs and cats. Gentle, positive reinforcement methods.",
    experience: 7,
    certifications: ["CAAB", "Fear Free Certified"],
    services: ["Cat Training", "Dog Walking", "Pet Sitting"],
    pricing: 60,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    rating: 4.7,
  },
]

export const mockBookings: Booking[] = [
  {
    id: "1",
    petId: "1",
    trainerId: "1",
    ownerId: "1",
    service: "Basic Training",
    date: new Date("2024-03-15"),
    time: "10:00",
    notes: "Focus on leash training",
    status: "confirmed",
  },
  {
    id: "2",
    petId: "2",
    trainerId: "2",
    ownerId: "1",
    service: "Cat Training",
    date: new Date("2024-03-16"),
    time: "14:00",
    status: "pending",
  },
]

export const mockPetStatuses: PetStatus[] = [
  {
    id: "1",
    petId: "1",
    trainerId: "1",
    walked: true,
    fed: true,
    played: true,
    resting: false,
    medication: false,
    notes: "Max had a great training session today!",
    createdAt: new Date("2024-03-15T12:00:00"),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    type: "booking-update",
    priority: "high",
    title: "Booking Confirmed",
    message: "Your training session with Sarah has been confirmed for March 15.",
    read: false,
    sentAt: new Date("2024-03-14"),
    createdAt: new Date("2024-03-14"),
  },
  {
    id: "2",
    userId: "1",
    type: "activity-update",
    priority: "medium",
    title: "Status Update",
    message: "Max just completed his morning walk!",
    read: true,
    sentAt: new Date("2024-03-15T09:30:00"),
    readAt: new Date("2024-03-15T09:35:00"),
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "3",
    userId: "1",
    type: "emotion-alert",
    priority: "high",
    title: "Mood Alert",
    message: "Max seems happy! Currently: Afternoon walk 😊",
    read: true,
    sentAt: new Date("2024-03-15T15:00:00"),
    readAt: new Date("2024-03-15T15:05:00"),
    createdAt: new Date("2024-03-15"),
  },
]

// Task Management Mock Data
export const mockTasks: Task[] = [
  {
    id: "1",
    petId: "1",
    ownerId: "1",
    title: "Morning walk",
    type: "walk",
    description: "Walk Max around the park for 25 minutes",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T09:00:00"),
    frequency: "daily",
    recurrencePattern: "0 9 * * *",
    timeWindow: { start: "08:30", end: "10:00" },
    assignedTo: "both",
    completionPhoto: "/walk-photo-1.jpg",
    completionNotes: "Great walk! Max loved the park",
    completedAt: new Date("2024-03-15T09:25:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T09:25:00"),
  },
  {
    id: "2",
    petId: "1",
    ownerId: "1",
    title: "Breakfast feeding",
    type: "meal",
    description: "Feed Max his morning kibble (2 cups)",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T08:00:00"),
    frequency: "daily",
    recurrencePattern: "0 8 * * *",
    timeWindow: { start: "07:30", end: "08:30" },
    assignedTo: "owner",
    completionNotes: "Max ate full portion, drank water",
    completedAt: new Date("2024-03-15T08:10:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T08:10:00"),
  },
  {
    id: "3",
    petId: "1",
    ownerId: "1",
    title: "Afternoon play session",
    type: "play",
    description: "Play time with toys, 30 minutes",
    priority: "medium",
    status: "completed",
    dueDate: new Date("2024-03-15T15:00:00"),
    frequency: "daily",
    recurrencePattern: "0 15 * * *",
    timeWindow: { start: "14:30", end: "16:00" },
    assignedTo: "caregiver",
    completionPhoto: "/play-photo-1.jpg",
    completionNotes: "Max is playful and energetic",
    completedAt: new Date("2024-03-15T15:25:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T15:25:00"),
  },
  {
    id: "4",
    petId: "1",
    ownerId: "1",
    title: "Arthritis medication",
    type: "medication",
    description: "Give Max his daily arthritis pill with peanut butter",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T12:00:00"),
    frequency: "daily",
    recurrencePattern: "0 12 * * *",
    assignedTo: "owner",
    completionNotes: "Pill given with peanut butter - no issues",
    completedAt: new Date("2024-03-15T12:15:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T12:15:00"),
  },
  {
    id: "5",
    petId: "1",
    ownerId: "1",
    title: "Evening walk",
    type: "walk",
    description: "Walk Max in the evening, 30 minutes",
    priority: "high",
    status: "pending",
    dueDate: new Date("2024-03-15T18:00:00"),
    frequency: "daily",
    recurrencePattern: "0 18 * * *",
    timeWindow: { start: "17:30", end: "19:00" },
    assignedTo: "caregiver",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "6",
    petId: "1",
    ownerId: "1",
    title: "Training session",
    type: "training",
    description: "Practice 'sit' and 'stay' commands, 15 minutes",
    priority: "medium",
    status: "completed",
    dueDate: new Date("2024-03-15T14:00:00"),
    frequency: "daily",
    recurrencePattern: "0 14 * * *",
    assignedTo: "caregiver",
    completionPhoto: "/training-photo-1.jpg",
    completionNotes: "Great progress! Max is responding better to commands",
    completedAt: new Date("2024-03-15T14:15:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T14:15:00"),
  },
]

// Daily Activity Mock Data
export const mockDailyActivities: DailyActivity[] = [
  {
    id: "1",
    petId: "1",
    caregiverId: "2",
    activityType: "walk",
    title: "Morning walk",
    description: "Walk around the park",
    duration: 25,
    startTime: new Date("2024-03-15T09:00:00"),
    endTime: new Date("2024-03-15T09:25:00"),
    photo: "/walk-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 92,
    caregiveNotes: "Max was happy and playful. Played with other dogs at the park.",
    location: { address: "Central Park, City" },
    aiVerified: true,
    createdAt: new Date("2024-03-15T09:25:00"),
  },
  {
    id: "2",
    petId: "1",
    caregiverId: "2",
    activityType: "meal",
    title: "Breakfast",
    description: "Morning feeding",
    startTime: new Date("2024-03-15T08:00:00"),
    photo: "/meal-photo-1.jpg",
    emotion: "content",
    emotionConfidence: 88,
    caregiveNotes: "Ate full portion, drank water well",
    aiVerified: true,
    createdAt: new Date("2024-03-15T08:10:00"),
  },
  {
    id: "3",
    petId: "1",
    caregiverId: "2",
    activityType: "training",
    title: "Training session",
    description: "Practice sit and stay commands",
    duration: 15,
    startTime: new Date("2024-03-15T14:00:00"),
    endTime: new Date("2024-03-15T14:15:00"),
    photo: "/training-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 85,
    caregiveNotes: "Great progress on 'stay' command. Very responsive today.",
    aiVerified: true,
    createdAt: new Date("2024-03-15T14:15:00"),
  },
  {
    id: "4",
    petId: "1",
    caregiverId: "2",
    activityType: "play",
    title: "Play session",
    description: "Interactive playtime with toys",
    duration: 30,
    startTime: new Date("2024-03-15T15:00:00"),
    endTime: new Date("2024-03-15T15:30:00"),
    photo: "/play-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 90,
    caregiveNotes: "Max is very energetic and engaged. Having fun!",
    aiVerified: true,
    createdAt: new Date("2024-03-15T15:30:00"),
  },
  {
    id: "5",
    petId: "1",
    caregiverId: "2",
    activityType: "rest",
    title: "Afternoon rest",
    description: "Nap time",
    startTime: new Date("2024-03-15T16:00:00"),
    photo: "/rest-photo-1.jpg",
    emotion: "calm",
    emotionConfidence: 95,
    caregiveNotes: "Napping peacefully on his favorite bed",
    aiVerified: true,
    createdAt: new Date("2024-03-15T16:30:00"),
  },
]

// Mood Entry Mock Data
export const mockMoodEntries: MoodEntry[] = [
  {
    id: "1",
    petId: "1",
    emotion: "playful",
    confidence: 92,
    photoUrl: "/walk-photo-1.jpg",
    timestamp: new Date("2024-03-15T09:00:00"),
    caregiverNotes: "Happy and energetic",
  },
  {
    id: "2",
    petId: "1",
    emotion: "content",
    confidence: 88,
    photoUrl: "/meal-photo-1.jpg",
    timestamp: new Date("2024-03-15T08:00:00"),
    caregiverNotes: "Ate well",
  },
  {
    id: "3",
    petId: "1",
    emotion: "calm",
    confidence: 95,
    photoUrl: "/rest-photo-1.jpg",
    timestamp: new Date("2024-03-15T16:30:00"),
    caregiverNotes: "Sleeping peacefully",
  },
  {
    id: "4",
    petId: "1",
    emotion: "playful",
    confidence: 90,
    photoUrl: "/play-photo-1.jpg",
    timestamp: new Date("2024-03-15T15:00:00"),
    caregiverNotes: "Very engaged in play",
  },
]

// Care Packages Mock Data
export const mockCarePackages: CarePackage[] = [
  {
    id: "1",
    type: "daily",
    name: "Daily Care Package",
    description: "Regular daily visits for walks, feeding, and play",
    basePrice: 45,
    visitsPerWeek: 5,
    includedServices: ["Walks", "Feeding", "Play sessions", "Medication administration"],
    features: ["Daily activity tracking", "Photo updates", "Emotion detection", "Task management"],
  },
  {
    id: "2",
    type: "overnight",
    name: "Overnight Care Package",
    description: "Overnight care while you're away",
    basePrice: 120,
    duration: "per night",
    includedServices: ["Evening routine", "Overnight supervision", "Morning routine", "Feeding"],
    features: ["24-hour monitoring", "Emergency support", "Timeline updates"],
  },
  {
    id: "3",
    type: "travel",
    name: "Travel Care Package",
    description: "Extended care for vacations and extended trips",
    basePrice: 85,
    duration: "per day",
    includedServices: ["Full daily routine", "Multiple walks", "Meals and medications", "Training reinforcement", "Emergency vet coordination"],
    features: ["Multiple daily updates", "AI emotion tracking", "Mood dashboard", "Complete transparency"],
  },
  {
    id: "4",
    type: "custom",
    name: "Custom Package",
    description: "Tailored care plan for unique needs",
    basePrice: 0,
    includedServices: [],
    features: ["Custom scheduling", "Special care needs", "Medical support", "Behavioral training"],
  },
]

// Notification Preferences Mock Data
export const mockNotificationPreferences: NotificationPreferences[] = [
  {
    userId: "1",
    pushNotificationsEnabled: true,
    emailEnabled: true,
    emailFrequency: "daily-digest",
    smsEnabled: false,
    quietHoursStart: "22:00",
    quietHoursEnd: "07:00",
    workModeEnabled: true,
    workModeStart: "09:00",
    workModeEnd: "17:00",
    notificationTypes: {
      taskReminders: true,
      activityUpdates: true,
      behavioralAlerts: true,
      healthAlerts: true,
      bookingUpdates: true,
      messages: true,
      systemUpdates: false,
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-15"),
  },
]

// Messages Mock Data
export const mockMessages: Message[] = [
  {
    id: "1",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Hi! Max had a great walk today. He was very happy and playful!",
    read: true,
    createdAt: new Date("2024-03-15T09:30:00"),
  },
  {
    id: "2",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "That's wonderful! Can he do an extra play session today?",
    read: true,
    createdAt: new Date("2024-03-15T10:00:00"),
  },
  {
    id: "3",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Absolutely! I'll add that to his schedule.",
    read: false,
    createdAt: new Date("2024-03-15T10:15:00"),
  },
]

// Reviews Mock Data
export const mockReviews: Review[] = [
  {
    id: "1",
    bookingId: "1",
    reviewerId: "1",
    caregiverId: "2",
    rating: 5,
    title: "Excellent caregiver!",
    comment: "Sarah was amazing with Max! She was professional, caring, and sent great updates throughout the day.",
    categories: {
      professionalism: 5,
      communication: 5,
      careQuality: 5,
      punctuality: 5,
    },
    createdAt: new Date("2024-03-15"),
  },
]

export const services = [
  "Basic Training",
  "Behavioral Modification",
  "Puppy Training",
  "Cat Training",
  "Dog Walking",
  "Pet Sitting",
  "Grooming",
  "Veterinary Care",
]

export const timeSlots = ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]
