import type { 
  User, Pet, Trainer, Booking, PetStatus, Notification, Task, DailyActivity, 
  MoodEntry, CarePackage, Message, Review, NotificationPreferences, CarePlan, PetProfile, Conversation 
} from "./types"

export const mockUsers: User[] = [
  {
    _id: "1",
    id: "1",
    email: "john@example.com",
    name: "John Smith",
    fullName: "John Smith",
    phone: "1234567890",
    role: "user",
    avatar: "/man-profile.png",
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    _id: "2",
    email: "sarah@example.com",
    name: "Sarah Johnson",
    fullName: "Sarah Johnson",
    phone: "0987654321",
    role: "trainer",
    avatar: "/woman-trainer-profile.jpg",
    createdAt: new Date("2024-02-01"),
  },
  {
    _id: "3",
    id: "3",
    email: "mike@example.com",
    name: "Mike Wilson",
    fullName: "Mike Wilson",
    phone: "5555555555",
    role: "trainer",
    avatar: "/man-trainer-profile.jpg",
    createdAt: new Date("2024-02-10"),
  },
  {
    _id: "4",
    id: "4",
    email: "admin@petcare.com",
    name: "System Admin",
    fullName: "System Admin",
    phone: "1111111111",
    role: "admin",
    avatar: "/placeholder.svg",
    createdAt: new Date("2024-03-01"),
  },
]

export const mockPets: Pet[] = [
  {
    _id: "1",
    id: "1",
    ownerId: "1",
    name: "Max",
    type: "dog",
    breed: "Golden Retriever",
    age: 3,
    medicalNotes: "Allergic to chicken",
    photo: "/golden-retriever.png",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20").toISOString(),
  },
  {
    _id: "2",
    ownerId: "1",
    name: "Luna",
    type: "cat",
    breed: "Persian",
    age: 2,
    photo: "/fluffy-persian-cat.png",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25").toISOString(),
  },
  {
    _id: "3",
    ownerId: "1",
    name: "Buddy",
    type: "dog",
    breed: "Labrador",
    age: 5,
    medicalNotes: "Takes daily vitamins",
    photo: "/labrador-dog.png",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05").toISOString(),
  },
]

export const mockTrainers: Trainer[] = [
  {
    _id: "1",
    id: "1",
    userId: "2",
    bio: "Certified dog trainer with 10+ years of experience. Specializing in behavioral training and puppy development.",
    experience: 10,
    certifications: ["CPDT-KA", "AKC CGC Evaluator"],
    services: ["Basic Training", "Behavioral Modification", "Puppy Training"],
    pricing: 75,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    rating: 4.9,
  },
  {
    _id: "2",
    id: "2",
    userId: "3",
    bio: "Animal behavior specialist focusing on both dogs and cats. Gentle, positive reinforcement methods.",
    experience: 7,
    certifications: ["CAAB", "Fear Free Certified"],
    services: ["Cat Training", "Dog Walking", "Pet Sitting"],
    pricing: 60,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    rating: 4.7,
  },
]

export const mockBookings: Booking[] = [
  {
    _id: "1",
    id: "1",
    petId: "1",
    trainerId: "1",
    ownerId: "1",
    service: "Basic Training",
    date: new Date("2024-03-15"),
    time: "10:00",
    notes: "Focus on leash training",
    status: "confirmed",
    packageType: "daily",
    customInstructions: "Max is very energetic. Prefers morning walks.",
    meetAndGreetScheduled: new Date("2024-03-10"),
    meetAndGreetCompleted: true,
    totalPrice: 45,
    paymentStatus: "paid",
    createdAt: new Date("2024-03-08"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    _id: "2",
    petId: "2",
    trainerId: "2",
    ownerId: "1",
    service: "Cat Training",
    date: new Date("2024-03-16"),
    time: "14:00",
    status: "pending",
    packageType: "custom",
    customInstructions: "Luna is shy. Use slow introduction techniques.",
    meetAndGreetScheduled: new Date("2024-03-13"),
    meetAndGreetCompleted: false,
    totalPrice: 95,
    paymentStatus: "pending",
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-12"),
  },
  {
    _id: "3",
    petId: "3",
    trainerId: "1",
    ownerId: "1",
    service: "Travel Care",
    date: new Date("2024-04-01"),
    time: "09:00",
    status: "confirmed",
    packageType: "travel",
    customInstructions: "Buddy needs regular bathroom breaks during travel. Keep him in air-conditioned space.",
    meetAndGreetScheduled: new Date("2024-03-25"),
    meetAndGreetCompleted: true,
    totalPrice: 120,
    paymentStatus: "paid",
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-25"),
  },
]

export const mockPetStatuses: PetStatus[] = [
  {
    id: "1",
    petId: "1",
    trainerId: "1",
    walked: true,
    fed: true,
    played: true,
    resting: false,
    medication: false,
    notes: "Max had a great training session today!",
    createdAt: new Date("2024-03-15T12:00:00"),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    type: "booking-update",
    priority: "high",
    title: "Booking Confirmed",
    message: "Your training session with Sarah has been confirmed for March 15.",
    read: false,
    sentAt: new Date("2024-03-14"),
    createdAt: new Date("2024-03-14"),
  },
  {
    _id: "2",
    _id: "2",
    userId: "1",
    type: "activity-update",
    priority: "medium",
    title: "Status Update",
    message: "Max just completed his morning walk!",
    read: true,
    sentAt: new Date("2024-03-15T09:30:00"),
    readAt: new Date("2024-03-15T09:35:00"),
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "3",
    userId: "1",
    type: "emotion-alert",
    priority: "high",
    title: "Mood Alert",
    message: "Max seems happy! Currently: Afternoon walk 😊",
    read: true,
    sentAt: new Date("2024-03-15T15:00:00"),
    readAt: new Date("2024-03-15T15:05:00"),
    createdAt: new Date("2024-03-15"),
  },
]

// Task Management Mock Data
export const mockTasks: Task[] = [
  {
    _id: "1",
    id: "1",
    petId: "1",
    ownerId: "1",
    title: "Morning walk",
    type: "walk",
    description: "Walk Max around the park for 25 minutes",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T09:00:00"),
    frequency: "daily",
    recurrencePattern: "0 9 * * *",
    timeWindow: { start: "08:30", end: "10:00" },
    assignedTo: "both",
    completionPhoto: "/walk-photo-1.jpg",
    completionNotes: "Great walk! Max loved the park",
    completedAt: new Date("2024-03-15T09:25:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T09:25:00"),
  },
  {
    _id: "2",
    _id: "2",
    petId: "1",
    ownerId: "1",
    title: "Breakfast feeding",
    type: "meal",
    description: "Feed Max his morning kibble (2 cups)",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T08:00:00"),
    frequency: "daily",
    recurrencePattern: "0 8 * * *",
    timeWindow: { start: "07:30", end: "08:30" },
    assignedTo: "owner",
    completionNotes: "Max ate full portion, drank water",
    completedAt: new Date("2024-03-15T08:10:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T08:10:00"),
  },
  {
    id: "3",
    petId: "1",
    ownerId: "1",
    title: "Afternoon play session",
    type: "play",
    description: "Play time with toys, 30 minutes",
    priority: "medium",
    status: "completed",
    dueDate: new Date("2024-03-15T15:00:00"),
    frequency: "daily",
    recurrencePattern: "0 15 * * *",
    timeWindow: { start: "14:30", end: "16:00" },
    assignedTo: "caregiver",
    completionPhoto: "/play-photo-1.jpg",
    completionNotes: "Max is playful and energetic",
    completedAt: new Date("2024-03-15T15:25:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T15:25:00"),
  },
  {
    id: "4",
    petId: "1",
    ownerId: "1",
    title: "Arthritis medication",
    type: "medication",
    description: "Give Max his daily arthritis pill with peanut butter",
    priority: "high",
    status: "completed",
    dueDate: new Date("2024-03-15T12:00:00"),
    frequency: "daily",
    recurrencePattern: "0 12 * * *",
    assignedTo: "owner",
    completionNotes: "Pill given with peanut butter - no issues",
    completedAt: new Date("2024-03-15T12:15:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T12:15:00"),
  },
  {
    id: "5",
    petId: "1",
    ownerId: "1",
    title: "Evening walk",
    type: "walk",
    description: "Walk Max in the evening, 30 minutes",
    priority: "high",
    status: "pending",
    dueDate: new Date("2024-03-15T18:00:00"),
    frequency: "daily",
    recurrencePattern: "0 18 * * *",
    timeWindow: { start: "17:30", end: "19:00" },
    assignedTo: "caregiver",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "6",
    petId: "1",
    ownerId: "1",
    title: "Training session",
    type: "training",
    description: "Practice 'sit' and 'stay' commands, 15 minutes",
    priority: "medium",
    status: "completed",
    dueDate: new Date("2024-03-15T14:00:00"),
    frequency: "daily",
    recurrencePattern: "0 14 * * *",
    assignedTo: "caregiver",
    completionPhoto: "/training-photo-1.jpg",
    completionNotes: "Great progress! Max is responding better to commands",
    completedAt: new Date("2024-03-15T14:15:00"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15T14:15:00"),
  },
]

// Daily Activity Mock Data
export const mockDailyActivities: DailyActivity[] = [
  {
    id: "1",
    petId: "1",
    caregiverId: "2",
    activityType: "walk",
    title: "Morning walk",
    description: "Walk around the park",
    duration: 25,
    startTime: new Date("2024-03-15T09:00:00"),
    endTime: new Date("2024-03-15T09:25:00"),
    photo: "/walk-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 92,
    caregiverNotes: "Max was happy and playful. Played with other dogs at the park.",
    location: { address: "Central Park, City" },
    aiVerified: true,
    createdAt: new Date("2024-03-15T09:25:00"),
  },
  {
    _id: "2",
    _id: "2",
    petId: "1",
    caregiverId: "2",
    activityType: "meal",
    title: "Breakfast",
    description: "Morning feeding",
    startTime: new Date("2024-03-15T08:00:00"),
    photo: "/meal-photo-1.jpg",
    emotion: "content",
    emotionConfidence: 88,
    caregiverNotes: "Ate full portion, drank water well",
    aiVerified: true,
    createdAt: new Date("2024-03-15T08:10:00"),
  },
  {
    id: "3",
    petId: "1",
    caregiverId: "2",
    activityType: "training",
    title: "Training session",
    description: "Practice sit and stay commands",
    duration: 15,
    startTime: new Date("2024-03-15T14:00:00"),
    endTime: new Date("2024-03-15T14:15:00"),
    photo: "/training-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 85,
    caregiverNotes: "Great progress on 'stay' command. Very responsive today.",
    aiVerified: true,
    createdAt: new Date("2024-03-15T14:15:00"),
  },
  {
    id: "4",
    petId: "1",
    caregiverId: "2",
    activityType: "play",
    title: "Play session",
    description: "Interactive playtime with toys",
    duration: 30,
    startTime: new Date("2024-03-15T15:00:00"),
    endTime: new Date("2024-03-15T15:30:00"),
    photo: "/play-photo-1.jpg",
    emotion: "playful",
    emotionConfidence: 90,
    caregiverNotes: "Max is very energetic and engaged. Having fun!",
    aiVerified: true,
    createdAt: new Date("2024-03-15T15:30:00"),
  },
  {
    id: "5",
    petId: "1",
    caregiverId: "2",
    activityType: "rest",
    title: "Afternoon rest",
    description: "Nap time",
    startTime: new Date("2024-03-15T16:00:00"),
    photo: "/rest-photo-1.jpg",
    emotion: "calm",
    emotionConfidence: 95,
    caregiverNotes: "Napping peacefully on his favorite bed",
    aiVerified: true,
    createdAt: new Date("2024-03-15T16:30:00"),
  },
]

// Mood Entry Mock Data
export const mockMoodEntries: MoodEntry[] = [
  {
    id: "1",
    petId: "1",
    emotion: "playful",
    confidence: 92,
    photoUrl: "/walk-photo-1.jpg",
    timestamp: new Date("2024-03-15T09:00:00"),
    caregiverNotes: "Happy and energetic",
  },
  {
    _id: "2",
    _id: "2",
    petId: "1",
    emotion: "content",
    confidence: 88,
    photoUrl: "/meal-photo-1.jpg",
    timestamp: new Date("2024-03-15T08:00:00"),
    caregiverNotes: "Ate well",
  },
  {
    id: "3",
    petId: "1",
    emotion: "calm",
    confidence: 95,
    photoUrl: "/rest-photo-1.jpg",
    timestamp: new Date("2024-03-15T16:30:00"),
    caregiverNotes: "Sleeping peacefully",
  },
  {
    id: "4",
    petId: "1",
    emotion: "playful",
    confidence: 90,
    photoUrl: "/play-photo-1.jpg",
    timestamp: new Date("2024-03-15T15:00:00"),
    caregiverNotes: "Very engaged in play",
  },
]

// Care Packages Mock Data
export const mockCarePackages: CarePackage[] = [
  {
    id: "1",
    type: "daily",
    name: "Daily Care Package",
    description: "Regular daily visits for walks, feeding, and play",
    basePrice: 45,
    visitsPerWeek: 5,
    includedServices: ["Walks", "Feeding", "Play sessions", "Medication administration"],
    features: ["Daily activity tracking", "Photo updates", "Emotion detection", "Task management"],
  },
  {
    _id: "2",
    _id: "2",
    type: "overnight",
    name: "Overnight Care Package",
    description: "Overnight care while you're away",
    basePrice: 120,
    duration: "per night",
    includedServices: ["Evening routine", "Overnight supervision", "Morning routine", "Feeding"],
    features: ["24-hour monitoring", "Emergency support", "Timeline updates"],
  },
  {
    id: "3",
    type: "travel",
    name: "Travel Care Package",
    description: "Extended care for vacations and extended trips",
    basePrice: 85,
    duration: "per day",
    includedServices: ["Full daily routine", "Multiple walks", "Meals and medications", "Training reinforcement", "Emergency vet coordination"],
    features: ["Multiple daily updates", "AI emotion tracking", "Mood dashboard", "Complete transparency"],
  },
  {
    id: "4",
    type: "custom",
    name: "Custom Package",
    description: "Tailored care plan for unique needs",
    basePrice: 0,
    includedServices: [],
    features: ["Custom scheduling", "Special care needs", "Medical support", "Behavioral training"],
  },
]

// Notification Preferences Mock Data
export const mockNotificationPreferences: NotificationPreferences[] = [
  {
    userId: "1",
    pushNotificationsEnabled: true,
    emailEnabled: true,
    emailFrequency: "daily-digest",
    smsEnabled: false,
    quietHoursStart: "22:00",
    quietHoursEnd: "07:00",
    workModeEnabled: true,
    workModeStart: "09:00",
    workModeEnd: "17:00",
    notificationTypes: {
      taskReminders: true,
      activityUpdates: true,
      behavioralAlerts: true,
      healthAlerts: true,
      bookingUpdates: true,
      messages: true,
      systemUpdates: false,
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-15"),
  },
]

// Messages Mock Data (consolidated later in this file)

export const services = [
  "Basic Training",
  "Behavioral Modification",
  "Puppy Training",
  "Cat Training",
  "Dog Walking",
  "Pet Sitting",
  "Grooming",
  "Veterinary Care",
]

export const timeSlots = ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]

// Care Plans
export const mockCarePlans: CarePlan[] = [
  {
    id: "1",
    bookingId: "1",
    petId: "1",
    trainerId: "1",
    specialNeeds: ["High energy", "Needs regular breaks"],
    dietaryRequirements: "Grain-free kibble, twice daily",
    medications: [
      {
        name: "Glucosamine",
        dosage: "500mg",
        frequency: "Once daily with food",
        instructions: "Mix with kibble in morning meal",
      },
    ],
    emergencyContacts: [
      {
        name: "John Smith",
        phone: "1234567890",
        relationship: "Owner",
      },
      {
        name: "Emily Smith",
        phone: "0987654321",
        relationship: "Spouse",
      },
    ],
    behavioralNotes: "Max can be reactive to other dogs on leash. Use positive reinforcement.",
    preferredActivities: ["Fetch", "Running", "Swimming"],
    restrictions: ["No off-leash in unfenced areas", "Avoid chocolate and grapes"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    _id: "2",
    _id: "2",
    bookingId: "3",
    petId: "3",
    trainerId: "1",
    specialNeeds: ["Anxiety in new environments", "Needs familiar blanket"],
    dietaryRequirements: "Sensitive stomach formula, three times daily",
    medications: [],
    emergencyContacts: [
      {
        name: "John Smith",
        phone: "1234567890",
        relationship: "Owner",
      },
    ],
    behavioralNotes: "Buddy is very loyal and responds well to routine. Maintain consistent schedule.",
    preferredActivities: ["Gentle walks", "Cuddles", "Puzzle toys"],
    restrictions: ["No loud noises", "Avoid sudden changes", "Keep stress levels low"],
    createdAt: new Date("2024-03-25"),
    updatedAt: new Date("2024-03-25"),
  },
]

// Pet Profiles - Enhanced detailed information
export const mockPetProfiles: PetProfile[] = [
  {
    id: "1",
    petId: "1",
    ownerId: "1",
    dateOfBirth: new Date("2021-03-15"),
    weight: 32,
    color: "Golden",
    microchipId: "985121000123456",
    veterinarian: {
      name: "Dr. Sarah Mitchell",
      clinic: "Sunny Paws Veterinary Clinic",
      phone: "555-0101",
      email: "contact@sunnypaws.com",
    },
    medicalHistory: [
      {
        date: new Date("2024-02-10"),
        condition: "Annual Checkup",
        treatment: "Vaccination update",
        notes: "Healthy, no issues noted",
      },
      {
        date: new Date("2024-01-15"),
        condition: "Ear Infection",
        treatment: "Antibiotic ear drops",
        notes: "Resolved after 2 weeks of treatment",
      },
    ],
    allergies: ["Chicken"],
    dietaryRequirements: "Grain-free kibble, high protein",
    foodBrand: "Royal Canin Grain-Free",
    mealsPerDay: 2,
    mealTimes: ["08:00", "18:00"],
    restrictions: ["Chicken", "Chocolate", "Grapes"],
    treats: ["Carrots", "Pumpkin", "Peanut butter (xylitol-free)"],
    waterIntakeGoal: 2000,
    medications: [
      {
        name: "Glucosamine",
        dosage: "500mg",
        frequency: "Once daily",
        startDate: new Date("2024-01-01"),
        instructions: "Mix with food",
        purpose: "Joint health",
      },
    ],
    supplements: [
      {
        name: "Omega-3 Fish Oil",
        dosage: "1000mg",
        frequency: "Once daily",
        purpose: "Coat and joint health",
      },
    ],
    temperament: ["Friendly", "Energetic", "Loving", "Loyal"],
    knownBehaviors: ["Jumps when excited", "Chases squirrels", "Loves to fetch"],
    fears: ["Thunder", "Vacuum cleaner"],
    triggers: ["Doorbell", "Car keys"],
    positiveBehaviors: ["Sits on command", "Comes when called", "Walks well on leash"],
    trainingStatus: "Well-trained, responsive to commands",
    emergencyContacts: [
      {
        name: "John Smith",
        phone: "1234567890",
        relationship: "Owner",
      },
      {
        name: "Emily Smith",
        phone: "0987654321",
        relationship: "Spouse",
      },
    ],
    insuranceProvider: "Pet Guardian",
    insurancePolicyNumber: "PG-12345678",
    preferredActivities: ["Fetch", "Running", "Swimming", "Hiking"],
    exerciseNeeds: "high",
    sleepSchedule: { bedtime: "22:00", wakeTime: "07:00" },
    grooming: {
      frequency: "Every 6 weeks",
      groomer: "Paws & Nails Grooming",
      lastGrooming: new Date("2024-02-20"),
    },
    vaccinations: [
      {
        name: "DHPP",
        date: new Date("2024-02-10"),
        expiryDate: new Date("2025-02-10"),
        vetName: "Dr. Sarah Mitchell",
      },
      {
        name: "Rabies",
        date: new Date("2024-02-10"),
        expiryDate: new Date("2027-02-10"),
        vetName: "Dr. Sarah Mitchell",
      },
    ],
    specialInstructions:
      "Max is very food motivated. Use high-value treats for training. Does not like having paws touched - handle carefully during grooming.",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    _id: "2",
    _id: "2",
    petId: "3",
    ownerId: "1",
    dateOfBirth: new Date("2022-06-10"),
    weight: 28,
    color: "Black",
    microchipId: "985121000654321",
    veterinarian: {
      name: "Dr. Sarah Mitchell",
      clinic: "Sunny Paws Veterinary Clinic",
      phone: "555-0101",
    },
    medicalHistory: [
      {
        date: new Date("2024-02-01"),
        condition: "Annual Checkup",
        treatment: "Vaccination update",
        notes: "Excellent health",
      },
    ],
    allergies: [],
    dietaryRequirements: "Sensitive stomach formula",
    foodBrand: "Hill's Science Diet Sensitive Stomach",
    mealsPerDay: 3,
    mealTimes: ["07:00", "13:00", "19:00"],
    restrictions: ["Rich foods", "Sudden diet changes"],
    treats: ["Plain chicken breast", "Rice"],
    waterIntakeGoal: 1500,
    medications: [],
    supplements: [],
    temperament: ["Calm", "Anxious", "Loyal", "Gentle"],
    knownBehaviors: ["Hides when stressed", "Shadow follows owner", "Reverses out of carriers"],
    fears: ["Car rides", "Strangers", "Changes in environment"],
    triggers: ["Loud noises", "New people"],
    positiveBehaviors: ["Cuddles", "Responds to name", "Uses litter box"],
    trainingStatus: "Not formally trained, but responds to routine",
    emergencyContacts: [
      {
        name: "John Smith",
        phone: "1234567890",
        relationship: "Owner",
      },
    ],
    insuranceProvider: "Pet Guardian",
    insurancePolicyNumber: "PG-87654321",
    preferredActivities: ["Gentle plays", "Window watching", "Lap sitting"],
    exerciseNeeds: "low",
    sleepSchedule: { bedtime: "21:00", wakeTime: "08:00" },
    grooming: {
      frequency: "Every 4 weeks",
      groomer: "Self-grooming primarily",
      lastGrooming: new Date("2024-02-15"),
    },
    vaccinations: [
      {
        name: "FVRCP",
        date: new Date("2024-02-01"),
        expiryDate: new Date("2025-02-01"),
        vetName: "Dr. Sarah Mitchell",
      },
    ],
    specialInstructions:
      "Buddy has severe anxiety. Please maintain routine and keep environment calm. Use gentle handling. Prefers familiar people. Provide safe space to hide if stressed.",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-01"),
  },
]

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["1", "2"],
    lastMessage: "Max seems to be adapting well! He's making great progress.",
    lastMessageDate: new Date("2024-02-28 14:30"),
    lastMessageSenderId: "2",
    unreadCount: 0,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-28"),
  },
  {
    id: "conv-2",
    participantIds: ["1", "3"],
    lastMessage: "Can we schedule a meet and greet for next week?",
    lastMessageDate: new Date("2024-02-27 10:15"),
    lastMessageSenderId: "1",
    unreadCount: 1,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-27"),
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  // Conversation 1: John & Sarah
  {
    id: "msg-1",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "Hi Sarah! I'd like to book Max for a training session this weekend.",
    read: true,
    createdAt: new Date("2024-02-10 09:00"),
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Hello John! That sounds great. What time works best for you? I'm available Saturday afternoon or Sunday morning.",
    read: true,
    createdAt: new Date("2024-02-10 09:30"),
  },
  {
    id: "msg-3",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "Saturday afternoon would be perfect! Maybe around 2 PM?",
    read: true,
    createdAt: new Date("2024-02-10 10:00"),
  },
  {
    id: "msg-4",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Perfect! Let's do Saturday at 2 PM. I'll bring some treats for Max to help him feel comfortable.",
    read: true,
    createdAt: new Date("2024-02-10 10:15"),
  },
  {
    id: "msg-5",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Just finished the training session with Max. He did wonderfully! He's very responsive and eager to learn.",
    read: true,
    createdAt: new Date("2024-02-12 15:00"),
  },
  {
    id: "msg-6",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "That's wonderful to hear! He seemed much more confident when I picked him up. Should we book another session?",
    read: true,
    createdAt: new Date("2024-02-12 16:30"),
  },
  {
    id: "msg-7",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Absolutely! I'd recommend continuing sessions weekly to reinforce his training. I'm available next Saturday at the same time.",
    read: true,
    createdAt: new Date("2024-02-12 17:00"),
  },
  {
    id: "msg-8",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "Great! Let's book next Saturday. Also, do you have any tips for practicing at home?",
    read: true,
    createdAt: new Date("2024-02-12 17:30"),
  },
  {
    id: "msg-9",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Of course! I'll send you a detailed training guide via email. The key is consistency - practice 10-15 minutes daily. Keep sessions fun and use high-value treats!",
    read: true,
    createdAt: new Date("2024-02-12 18:00"),
  },
  {
    id: "msg-10",
    conversationId: "conv-1",
    senderId: "1",
    receiverId: "2",
    content: "Thanks Sarah! You've been amazing. Max loves working with you.",
    read: true,
    createdAt: new Date("2024-02-12 18:30"),
  },
  {
    id: "msg-11",
    conversationId: "conv-1",
    senderId: "2",
    receiverId: "1",
    content: "Max seems to be adapting well! He's making great progress.",
    read: true,
    createdAt: new Date("2024-02-28 14:30"),
  },

  // Conversation 2: John & Mike
  {
    id: "msg-12",
    conversationId: "conv-2",
    senderId: "1",
    receiverId: "3",
    content: "Hi Mike! I'm interested in your overnight pet care service. Can you tell me more about it?",
    read: true,
    createdAt: new Date("2024-02-15 11:00"),
  },
  {
    id: "msg-13",
    conversationId: "conv-2",
    senderId: "3",
    receiverId: "1",
    content: "Hi John! Of course. I offer overnight care for pets, which includes feeding, bathroom breaks, and monitoring throughout the night.",
    read: true,
    createdAt: new Date("2024-02-15 11:30"),
  },
  {
    id: "msg-14",
    conversationId: "conv-2",
    senderId: "3",
    receiverId: "1",
    content: "I have 10+ years of experience and maintain a calm, nurturing environment. Pets often sleep better knowing someone's there.",
    read: true,
    createdAt: new Date("2024-02-15 11:35"),
  },
  {
    id: "msg-15",
    conversationId: "conv-2",
    senderId: "1",
    receiverId: "3",
    content: "That sounds perfect for Max. He sometimes has anxiety at night. How much is your overnight rate?",
    read: true,
    createdAt: new Date("2024-02-15 12:00"),
  },
  {
    id: "msg-16",
    conversationId: "conv-2",
    senderId: "3",
    receiverId: "1",
    content: "My overnight care is $75 per night. I provide daily photo updates and morning notes about how they slept and behaved.",
    read: true,
    createdAt: new Date("2024-02-15 12:30"),
  },
  {
    id: "msg-17",
    conversationId: "conv-2",
    senderId: "1",
    receiverId: "3",
    content: "Excellent! That's very reasonable. Do you offer any trial period or meet and greet?",
    read: true,
    createdAt: new Date("2024-02-15 13:00"),
  },
  {
    id: "msg-18",
    conversationId: "conv-2",
    senderId: "3",
    receiverId: "1",
    content: "Yes! I always recommend a meet and greet first. It helps the pet get comfortable with me. We can do a 1-hour session to see if it's a good fit.",
    read: true,
    createdAt: new Date("2024-02-15 13:30"),
  },
  {
    id: "msg-19",
    conversationId: "conv-2",
    senderId: "1",
    receiverId: "3",
    content: "Perfect! When are you available?",
    read: true,
    createdAt: new Date("2024-02-15 14:00"),
  },
  {
    id: "msg-20",
    conversationId: "conv-2",
    senderId: "3",
    receiverId: "1",
    content: "I'm available most evenings after 5 PM and all day on weekends. What works best for you?",
    read: true,
    createdAt: new Date("2024-02-15 14:30"),
  },
  {
    id: "msg-21",
    conversationId: "conv-2",
    senderId: "1",
    receiverId: "3",
    content: "Can we schedule a meet and greet for next week?",
    read: false,
    createdAt: new Date("2024-02-27 10:15"),
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: "review-1",
    bookingId: "1",
    reviewerId: "1",
    caregiverId: "2",
    rating: 5,
    title: "Excellent trainer! Max loved it!",
    comment: "Sarah is absolutely wonderful with Max. She's patient, knowledgeable, and genuinely cares about each dog's wellbeing. Max has shown such great improvement in his behavior and confidence. Highly recommended!",
    categories: {
      professionalism: 5,
      communication: 5,
      careQuality: 5,
      punctuality: 5,
    },
    createdAt: new Date("2024-02-14 16:30"),
  },
  {
    id: "review-2",
    bookingId: "3",
    reviewerId: "1",
    caregiverId: "3",
    rating: 4,
    title: "Great service and very reliable",
    comment: "Mike provided excellent overnight care for my dog. He was very responsive to my concerns and sent daily updates with photos. The only minor thing was that he arrived 15 minutes late once, but overall very satisfied.",
    categories: {
      professionalism: 4,
      communication: 5,
      careQuality: 4,
      punctuality: 4,
    },
    createdAt: new Date("2024-02-12 10:00"),
  },
  {
    id: "review-3",
    bookingId: "2",
    reviewerId: "1",
    caregiverId: "2",
    rating: 5,
    title: "Perfect! Five stars across the board",
    comment: "Sarah took excellent care of Luna while we were away. She's professional, punctual, and really understands feline behavior. Luna was relaxed when we returned. Worth every penny!",
    categories: {
      professionalism: 5,
      communication: 5,
      careQuality: 5,
      punctuality: 5,
    },
    createdAt: new Date("2024-02-10 14:15"),
  },
]
